# Generated by Django 5.0.3 on 2024-04-12 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='descripcionCategoria',
            field=models.CharField(default='x', max_length=500, verbose_name='Descripcion categoria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categoria',
            name='rutaImagen',
            field=models.CharField(default='x', max_length=200, verbose_name='Imagen categoria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categoria',
            name='url',
            field=models.CharField(default='x', max_length=500, verbose_name='URL categoria'),
            preserve_default=False,
        ),
    ]
