# Generated by Django 5.0.3 on 2024-04-12 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_categoria_descripcioncategoria_categoria_rutaimagen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id del producto')),
                ('nombreProducto', models.CharField(max_length=50, verbose_name='Nombre del producto')),
                ('precioProducto', models.IntegerField(verbose_name='Id del producto')),
                ('stock_producto', models.IntegerField(verbose_name='Stock del producto')),
                ('idCategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categoria')),
            ],
        ),
    ]
