# Generated by Django 5.0.3 on 2024-04-12 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rutCliente', models.IntegerField(primary_key=True, serialize=False, verbose_name='Rut del cliente')),
                ('nombreCliente', models.CharField(max_length=150, verbose_name='Nombre del cliente')),
                ('correoElectronico', models.CharField(max_length=50, verbose_name='Correo del cliente')),
                ('claveSeguridad', models.CharField(max_length=50, verbose_name='Clave del cliente')),
                ('fechaNacimiento', models.CharField(max_length=50, verbose_name='Fecha de nacimiento del cliente')),
                ('direccionCliente', models.CharField(max_length=150, verbose_name='Direccion del cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('idCompra', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de la compra')),
                ('fecha', models.DateTimeField(verbose_name='Fecha de compra')),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cliente')),
                ('productos', models.ManyToManyField(to='app.producto')),
            ],
        ),
    ]
