# Generated by Django 5.0.3 on 2024-04-12 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_producto_rutaimagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precioProducto',
            field=models.IntegerField(verbose_name='Precio del producto'),
        ),
    ]
