# Generated by Django 5.0.3 on 2024-04-12 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_producto_precioproducto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='url',
        ),
    ]
