# Generated by Django 5.0.3 on 2024-04-12 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_carrito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='idCliente',
        ),
        migrations.AddField(
            model_name='carrito',
            name='username',
            field=models.CharField(default='x', max_length=50, verbose_name='Username del cliente'),
            preserve_default=False,
        ),
    ]
