# Generated by Django 5.0.3 on 2024-04-15 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_carrito_productos_itemcarrito_carrito_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemcarrito',
            old_name='idProducto',
            new_name='producto',
        ),
    ]
